apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  annotations:
    app.openshift.io/runtime: nodejs
  name: ryuto-nakano-pipeline-from-scratch-pipeline-react
spec:
  workspaces:
    - name: pipeline-shared-data
      description: |
        This workspace stores the cloned repository and is available to all steps
  params:
    - name: image-repo
      type: string
      description: Docker image name
      default: quay.io/ryuto-nakano/ryuto-nakano-react-app
  tasks:
    - name: clone-repository
      params:
        - name: url
          value: https://github.com/cloud-native-garage-method-japan-cohort/ryuto-nakano-react-app.git
      taskRef:
        kind: Task
        name: git-clone
      workspaces:
        - name: output
          workspace: pipeline-shared-data
    - name: install-dependencies
      taskRef:
        name: npm
      params:
        - name: ARGS
          value:
            - clean-install
        # バージョンを指定
        - name: IMAGE
          value: "docker.io/library/node:20.15.1"
      workspaces:
        - name: source
          workspace: pipeline-shared-data
      runAfter:
        - clone-repository
    - name: run-tests
      taskRef:
        name: npm
      params:
        - name: ARGS
          value:
            - test
        # バージョンを指定
        - name: IMAGE
          value: "docker.io/library/node:20.15.1"
      workspaces:
        - name: source
          workspace: pipeline-shared-data
      runAfter:
        - install-dependencies
    - name: build-image
      runAfter:
        - run-tests
      params:
        - name: IMAGE
          value: "$(params.image-repo):$(tasks.clone-repository.results.commit)"
      taskRef:
        kind: Task
        name: buildah
      workspaces:
        - name: source
          workspace: pipeline-shared-data